name: Build Package

on:
  push:
    branches: [ main ]
    tags:
    - '*'
  pull_request:
    branches: [ main ]

jobs:
  build-bigsur:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build ( macOS x64)
      run: xcodebuild clean build -scheme LayoutSwitcherPack -destination 'platform=macOS,arch=x86_64' -derivedDataPath ${{ github.workspace }}/build CODE_SIGNING_ALLOWED=NO
    # GitHub provides Apple Silicon runners on macos-14.
    - name: List files in the repository
      run: |
        ls ${{ github.workspace }}
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        path: '.'
        type: 'zip'
        filename: 'LayoutSwitcher.zip'
        exclusions: '*.git* .editorconfig' 
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "LayoutSwitcher.zip"
        token: ${{ secrets.GITHUB_TOKEN }}

  build-m1:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v3
    - name: Build ( macOS arm64)
      run: xcodebuild clean build -scheme LayoutSwitcherPack -destination 'platform=macOS,arch=arm64' -derivedDataPath ${{ github.workspace }}/build-arm64 CODE_SIGNING_ALLOWED=NO
